#file: noinspection SpellCheckingInspection
services:
  cw2-bot:
    build:
      context: .
    volumes:
      - ./build:/build/
    env_file:
      - .env
    depends_on:
      cw2-db:
        condition: service_healthy
  cw2-db:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      - cw2-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=urfu_cw1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "localhost:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  cw2-mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
     - cw2-mongo-data:/data/db
#    ports:
#      - "localhost:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cw2-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "localhost:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@cw2-mongo:27017/
      ME_CONFIG_BASICAUTH: false
volumes:
  cw2-postgres-data:
  cw2-mongo-data:
